/* Untyped file generated by genType. */

import Render_question_form from './Render_question_form';

import * as React from 'react';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(children) { return ReasonReact.wrapJsForReason(Render_question_form, {}, children); };
