/* Untyped file generated by genType. */

import * as RR_AppBS from './RR_App.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const RR_App = ReasonReact.wrapReasonForJs(
  RR_AppBS.component,
  (function _(jsProps) {
     return RR_AppBS.make(jsProps.children);
  }));

export default RR_App;
