/* Untyped file generated by genType. */

import * as RRAppBS from './RRApp.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const RRApp = ReasonReact.wrapReasonForJs(
  RRAppBS.component,
  (function _(jsProps) {
     return RRAppBS.make(jsProps.children);
  }));

export default RRApp;
