/* Untyped file generated by genType. */

import {default as makeNotChecked} from './AutosuggestTextInput.js';

// In case of type error, check the type of 'make' in 'AutosuggestTextInput.re' and './AutosuggestTextInput.js'.
export const makeTypeChecked = makeNotChecked;

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = makeTypeChecked;
