/* Untyped file generated by genType. */

const $$toRE316431264 = {"row": 5693978, "column": -963948842, "row-responsive": 329567801};

const $$toRE222145588 = {"start": 67859554, "end": -1021944796, "center": 98248149, "between": -424439352, "around": 906229837};

import * as BoxBS from './Box.bs';

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const Box = ReasonReact.wrapReasonForJs(
  BoxBS.component,
  (function _(jsProps) {
     return Curry._6(BoxBS.make, $$toRE316431264[jsProps.direction], $$toRE222145588[jsProps.alignContent], $$toRE222145588[jsProps.justifyContent], $$toRE222145588[jsProps.alignItems], jsProps.className, jsProps.children);
  }));

export default Box;
