/* Untyped file generated by genType. */

const $$toRE390218611 = {"column": -963948842, "row": 5693978, "row_responsive": 329567801};

const $$toRE387747977 = {"around": 906229837, "between": -424439352, "center": 98248149, "end_": -1021944796, "start": 67859554};

import * as BoxBS from './Box.bs';

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const Box = ReasonReact.wrapReasonForJs(
  BoxBS.component,
  (function _(jsProps) {
     return Curry._4(BoxBS.make, $$toRE390218611[jsProps.direction], $$toRE387747977[jsProps.alignContent], jsProps.className, jsProps.children);
  }));

export default Box;
