/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as DottedLabelBS from './DottedLabel.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const DottedLabel = ReasonReact.wrapReasonForJs(
  DottedLabelBS.component,
  (function _(jsProps) {
     return Curry._3(DottedLabelBS.make, jsProps.label, jsProps.value, jsProps.children);
  }));

export default DottedLabel;
