/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as RadioButtonBS from './RadioButton.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const RadioButton = ReasonReact.wrapReasonForJs(
  RadioButtonBS.component,
  (function _(jsProps) {
     return Curry._6(RadioButtonBS.make, jsProps.label, jsProps.name, jsProps.value, jsProps.checked, jsProps.onChange, jsProps.children);
  }));

export default RadioButton;
