/* Untyped file generated by genType. */

import PhieuDieuTra_Main from './PhieuDieuTra_Main';

import * as React from 'react';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(initialValue, onSave, onSaveDraft, children) { return ReasonReact.wrapJsForReason(PhieuDieuTra_Main, {initialValue: initialValue, onSave: onSave, onSaveDraft: onSaveDraft}, children); };
