/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as PDT_RenderTinhTrangNhuCauHamTrenBS from './PDT_RenderTinhTrangNhuCauHamTren.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const PDT_RenderTinhTrangNhuCauHamTren = ReasonReact.wrapReasonForJs(
  PDT_RenderTinhTrangNhuCauHamTrenBS.component,
  (function _(jsProps) {
     return Curry._3(PDT_RenderTinhTrangNhuCauHamTrenBS.make, jsProps.value, jsProps.onChange, jsProps.children);
  }));

export default PDT_RenderTinhTrangNhuCauHamTren;
