/* Untyped file generated by genType. */

import * as PDT_TableSchemaBS from './PDT_TableSchema.bs';

export const Tinh_trang_ham_tren_table = PDT_TableSchemaBS.Tinh_trang_ham_tren[4];

export const Tinh_trang_ham_duoi_table = PDT_TableSchemaBS.Tinh_trang_ham_duoi[4];

export const OHIS_table = PDT_TableSchemaBS.OHIS[1];

export const MocChenChuc_table = PDT_TableSchemaBS.MocChenChuc[1];

export const MIH_table = PDT_TableSchemaBS.MIH[1];

export const CPI_table = PDT_TableSchemaBS.CPI[1];
