/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as PDT_RenderTinhTrangNhuCauBS from './PDT_RenderTinhTrangNhuCau.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const HamTren = ReasonReact.wrapReasonForJs(
  PDT_RenderTinhTrangNhuCauBS.HamTren[0],
  (function _(jsProps) {
     return Curry._3(PDT_RenderTinhTrangNhuCauBS.HamTren[1], jsProps.value, jsProps.onChange, jsProps.children);
  }));

export const HamDuoi = ReasonReact.wrapReasonForJs(
  PDT_RenderTinhTrangNhuCauBS.HamDuoi[0],
  (function _(jsProps) {
     return Curry._3(PDT_RenderTinhTrangNhuCauBS.HamDuoi[1], jsProps.value, jsProps.onChange, jsProps.children);
  }));
