/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as PDT_AllTablesBS from './PDT_AllTables.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const OHIS = ReasonReact.wrapReasonForJs(
  PDT_AllTablesBS.OHIS[0],
  (function _(jsProps) {
     return Curry._3(PDT_AllTablesBS.OHIS[1], jsProps.value, jsProps.onChange, jsProps.children);
  }));

export const CPI = ReasonReact.wrapReasonForJs(
  PDT_AllTablesBS.CPI[0],
  (function _(jsProps) {
     return Curry._3(PDT_AllTablesBS.CPI[1], jsProps.value, jsProps.onChange, jsProps.children);
  }));

export const MIH = ReasonReact.wrapReasonForJs(
  PDT_AllTablesBS.MIH[0],
  (function _(jsProps) {
     return Curry._3(PDT_AllTablesBS.MIH[1], jsProps.value, jsProps.onChange, jsProps.children);
  }));

export const MocChenChuc = ReasonReact.wrapReasonForJs(
  PDT_AllTablesBS.MocChenChuc[0],
  (function _(jsProps) {
     return Curry._3(PDT_AllTablesBS.MocChenChuc[1], jsProps.value, jsProps.onChange, jsProps.children);
  }));
