/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as PDT_RenderTinhTrangNhuCauHamDuoiBS from './PDT_RenderTinhTrangNhuCauHamDuoi.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const PDT_RenderTinhTrangNhuCauHamDuoi = ReasonReact.wrapReasonForJs(
  PDT_RenderTinhTrangNhuCauHamDuoiBS.component,
  (function _(jsProps) {
     return Curry._3(PDT_RenderTinhTrangNhuCauHamDuoiBS.make, jsProps.value, jsProps.onChange, jsProps.children);
  }));

export default PDT_RenderTinhTrangNhuCauHamDuoi;
