/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as PhieuDieuTra_RenderTinhTrangNhuCauBS from './PhieuDieuTra_RenderTinhTrangNhuCau.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const PhieuDieuTra_RenderTinhTrangNhuCau = ReasonReact.wrapReasonForJs(
  PhieuDieuTra_RenderTinhTrangNhuCauBS.component,
  (function _(jsProps) {
     return Curry._3(PhieuDieuTra_RenderTinhTrangNhuCauBS.make, jsProps.value, jsProps.onChange, jsProps.children);
  }));

export default PhieuDieuTra_RenderTinhTrangNhuCau;
