/* Untyped file generated by genType. */

import * as Curry from 'bs-platform/lib/es6/curry.js';

import * as PhieuDieuTra_RenderTinhTrangNhuCauHamDuoiBS from './PhieuDieuTra_RenderTinhTrangNhuCauHamDuoi.bs';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

export const PhieuDieuTra_RenderTinhTrangNhuCauHamDuoi = ReasonReact.wrapReasonForJs(
  PhieuDieuTra_RenderTinhTrangNhuCauHamDuoiBS.component,
  (function _(jsProps) {
     return Curry._3(PhieuDieuTra_RenderTinhTrangNhuCauHamDuoiBS.make, jsProps.value, jsProps.onChange, jsProps.children);
  }));

export default PhieuDieuTra_RenderTinhTrangNhuCauHamDuoi;
