/* Untyped file generated by genType. */

import {CheckBox as makeNotChecked} from 'grommet';

// In case of type error, check the type of 'make' in 'Grommet__CheckBox.re' and 'grommet'.
export const makeTypeChecked = makeNotChecked;

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = makeTypeChecked;
