/* Untyped file generated by genType. */

import {Markdown as Markdown} from 'grommet';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function (children) { return ReasonReact.wrapJsForReason(Markdown, {}, children); };
