/* Untyped file generated by genType. */

import {TextInput as TextInput} from 'grommet';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function (dropAlign, dropHeight, dropTarget, focusIndicator, id, messages, name, onChange, onSelect, onSuggestionsClose, onSuggestionsOpen, placeholder, plain, size, suggestions, value, type, children) { return ReasonReact.wrapJsForReason(TextInput, {dropAlign: dropAlign, dropHeight: dropHeight, dropTarget: dropTarget, focusIndicator: focusIndicator, id: id, messages: messages, name: name, onChange: onChange, onSelect: onSelect, onSuggestionsClose: onSuggestionsClose, onSuggestionsOpen: onSuggestionsOpen, placeholder: placeholder, plain: plain, size: size, suggestions: suggestions, value: value, type: type}, children); };
