/* Untyped file generated by genType. */

import GHeading from './GHeading';

import * as React from 'react';

const $$toJS681176817 = {"-634588120": "align_start", "218723151": "align_center", "-520296927": "align_end", "933804875": "align_stretch"};

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(a11yTitle, alignSelf, color, gridArea, size, textAlign, level, children) { return ReasonReact.wrapJsForReason(GHeading, {a11yTitle: a11yTitle, alignSelf: (alignSelf == null ? alignSelf : $$toJS681176817[alignSelf]), color: color, gridArea: gridArea, size: size, textAlign: textAlign, level: level}, children); };
