/* Untyped file generated by genType. */

import GButton from './GButton';

import * as React from 'react';

const $$toJS681176817 = {"-634588120": "align_start", "218723151": "align_center", "-520296927": "align_end", "933804875": "align_stretch"};

const $$toJS711408956 = {"-639606286": "button", "-423081521": "reset", "436623384": "submit"};

const $$toJS746122097 = {"-96584369": "xsmall", "-9768761": "small", "-20425611": "medium", "-272944197": "large", "-359759805": "xlarge"};

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(a11yTitle, active, alignSelf, color, disabled, fill, focusIndicator, gridArea, hoverIndicator, href, label, margin, onClick, plain, primary, reverse, typ, icon, as_, children) { return ReasonReact.wrapJsForReason(GButton, {a11yTitle: a11yTitle, active: active, alignSelf: (alignSelf == null ? alignSelf : $$toJS681176817[alignSelf]), color: color, disabled: disabled, fill: fill, focusIndicator: focusIndicator, gridArea: gridArea, hoverIndicator: hoverIndicator, href: href, label: label, margin: (margin == null ? margin : $$toJS746122097[margin]), onClick: onClick, plain: plain, primary: primary, reverse: reverse, typ: (typ == null ? typ : $$toJS711408956[typ]), icon: icon, as_: as_}, children); };
