/* Untyped file generated by genType. */

import GBox from './GBox';

import * as React from 'react';

const $$toJS658478831 = {"-129112121": "xxsmall", "-96584369": "xsmall", "-9768761": "small", "-20425611": "medium", "-272944197": "large", "-359759805": "xlarge", "-1010505329": "full", "-989320781": "1/2", "802877217": "1/3", "-1012272581": "2/3", "619062391": "1/4", "951396241": "2/4", "772622207": "3/4", "-1065951377": "auto"};

const $$toJS750567599 = {"-634105323": "start", "326386882": "center", "1053490894": "end", "-826986888": "stretch"};

const $$toJS316431264 = {"5693978": "row", "-963948842": "column", "329567801": "row-responsive"};

const $$toJS358268177 = {"-922086728": "none", "-96584369": "xsmall", "-9768761": "small", "-20425611": "medium", "-272944197": "large", "-359759805": "xlarge"};

const $$toJS746122097 = {"-96584369": "xsmall", "-9768761": "small", "-20425611": "medium", "-272944197": "large", "-359759805": "xlarge"};

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(a11yTitle, align, alignContent, alignSelf, animation, background, basis, border, direction, elevation, fill, flex, gap, gridArea, height, justify, margin, overflow, pad, responsive, round, width, wrap, style, as, children) { return ReasonReact.wrapJsForReason(GBox, {a11yTitle: a11yTitle, align: align, alignContent: alignContent, alignSelf: (alignSelf == null ? alignSelf : $$toJS750567599[alignSelf]), animation: animation, background: background, basis: (basis == null ? basis : $$toJS658478831[basis]), border: border, direction: (direction == null ? direction : $$toJS316431264[direction]), elevation: (elevation == null ? elevation : $$toJS358268177[elevation]), fill: fill, flex: flex, gap: (gap == null ? gap : $$toJS746122097[gap]), gridArea: gridArea, height: height, justify: justify, margin: (margin == null ? margin : $$toJS746122097[margin]), overflow: overflow, pad: pad, responsive: responsive, round: round, width: width, wrap: wrap, style: style, as: as}, children); };
