/* Untyped file generated by genType. */

import GTextInput from "./GTextInput";

import * as React from "react";

import * as ReasonReact from "reason-react/src/ReasonReact.js";

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(name, id, value, placeholder, type, children) {
  return ReasonReact.wrapJsForReason(
    GTextInput,
    {
      name: name,
      id: id,
      value: value,
      placeholder: placeholder,
      type: type,
      plain: true,
      suggestions: ["hey", "there"],
      messages: { enterSelection: "enterSelections" },
    },
    children
  );
};
