/* Untyped file generated by genType. */

import {Text as Text} from 'grommet';

const $$toJS41896662 = {"745566416": "start", "903023015": "center", "-94607159": "end"};

const $$toJS806027553 = {"-634105323": "start", "326386882": "center", "1053490894": "end", "-826986888": "stretch"};

const $$toJS943451479 = {"812216871": "normal", "-1055161979": "bold"};

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function (a11yTitle, alignSelf, color, gridArea, margin, size, textAlign, truncate, weight, level, as, children) { return ReasonReact.wrapJsForReason(Text, {a11yTitle: a11yTitle, alignSelf: (alignSelf == null ? alignSelf : $$toJS806027553[alignSelf]), color: color, gridArea: gridArea, margin: margin, size: size, textAlign: (textAlign == null ? textAlign : $$toJS41896662[textAlign]), truncate: truncate, weight: (weight == null ? weight : $$toJS943451479[weight]), level: level, as: as}, children); };
