/* Untyped file generated by genType. */

import GRadioButton from './GRadioButton';

import * as React from 'react';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(checked, disabled, id, label, name, value, onChange, children) { return ReasonReact.wrapJsForReason(GRadioButton, {checked: checked, disabled: disabled, id: id, label: label, name: name, value: value, onChange: onChange}, children); };
