/* Untyped file generated by genType. */

import GText from './GText';

import * as React from 'react';

const $$toJS434834571 = {"745566416": "ta_start", "903023015": "ta_center", "-94607159": "ta_end"};

const $$toJS681176817 = {"-634588120": "align_start", "218723151": "align_center", "-520296927": "align_end", "933804875": "align_stretch"};

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(a11yTitle, alignSelf, color, gridArea, margin, size, textAlign, truncate, weight, level, as, children) { return ReasonReact.wrapJsForReason(GText, {a11yTitle: a11yTitle, alignSelf: (alignSelf == null ? alignSelf : $$toJS681176817[alignSelf]), color: color, gridArea: gridArea, margin: margin, size: size, textAlign: (textAlign == null ? textAlign : $$toJS434834571[textAlign]), truncate: truncate, weight: weight, level: level, as: as}, children); };
